compressionLevel: 0
defaultSemverRangePrefix: ""
enableGlobalCache: false
enableMessageNames: false
nodeLinker: node-modules
plugins:
  - path: bundles/@yarnpkg/plugin-conventional-version.dev.cjs
supportedArchitectures:
  cpu:
    - x64
    - arm64
  os:
    - linux
    - darwin
