compressionLevel: mixed

defaultSemverRangePrefix: ""

enableGlobalCache: false

enableMessageNames: false

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-postinstall-dev.cjs
    spec: "https://raw.githubusercontent.com/sachinraja/yarn-plugin-postinstall-dev/main/bundles/%40yarnpkg/plugin-postinstall-dev.js"
  - path: bundles/@yarnpkg/plugin-conventional-version.dev.cjs

supportedArchitectures:
  cpu:
    - x64
    - arm64
  os:
    - linux
    - darwin

yarnPath: .yarn/releases/yarn-4.0.1.cjs
